#!/usr/bin/env python3
"""Verify the exact Persona reel bytes that ship in the desktop bundle."""

from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path, PurePosixPath
import sys

sys.dont_write_bytecode = True


ROOT = Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "apps" / "desktop" / "ui" / "persona-reels"
SELECTOR_PATH = ROOT / "scripts" / "select-persona-reels.py"
EXPECTED_PERSONAS = (
    "claude",
    "gemini",
    "grok",
    "chatgpt",
    "deepseek",
    "qwen",
    "mistral",
    "venice",
    "sakana",
    "perplexity",
    "glm",
    "kimi",
    "hunyuan",
    "minimax",
    "nemotron",
    "cohere",
    "mimo",
)
EXPECTED_LAYERS = 402
EXPECTED_PNG_BYTES = 35_140_885
EXPECTED_MANIFEST_SHA256 = "318924b3dd6fb575fdf36d91572b5d7b93ae9c8d6e74f366e93bb1b920b550ce"
EXPECTED_NOTICE_SHA256 = "a4e57bed389387dbf8d7aa5b5351469cf9abe10e02ee52a9ee374c81e83f87b9"
RUNTIME_PREFIX = (
    "// Generated by scripts/select-persona-reels.py; do not edit.\n"
    "globalThis.__AI_SISTER_PERSONA_REELS__ = "
)


def die(message: str) -> None:
    raise SystemExit(f"persona reel check failed: {message}")


def load_selector():
    spec = importlib.util.spec_from_file_location("ai_sister_reel_selector", SELECTOR_PATH)
    if spec is None or spec.loader is None:
        die("cannot load selector")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    selector = load_selector()
    manifest_raw = (BUNDLE / "manifest.json").read_bytes()
    if hashlib.sha256(manifest_raw).hexdigest() != EXPECTED_MANIFEST_SHA256:
        die("exact manifest bytes changed without a new reviewed pin")
    manifest = selector.read_json_object(BUNDLE / "manifest.json")
    selector._validate_sanitized_manifest(manifest)

    if manifest.get("schema") != "ai-sister/persona-reels/v1":
        die("unexpected schema")
    if manifest.get("rights_review") != "approved-owner-grant":
        die("owner grant is not approved")
    grant = manifest.get("owner_grant")
    if not isinstance(grant, dict) or grant.get("grantor") != "Ted Huang":
        die("owner grant is missing")
    if grant.get("license") != "excluded-from-Apache-2.0":
        die("image license boundary changed")
    if "local layered rendering and animation" not in str(grant.get("scope", "")):
        die("owner grant does not cover the shipped runtime use")
    if manifest.get("notice") != "NOTICE.md":
        die("NOTICE binding changed")
    notice_raw = (BUNDLE / "NOTICE.md").read_bytes()
    if hashlib.sha256(notice_raw).hexdigest() != EXPECTED_NOTICE_SHA256:
        die("exact NOTICE bytes changed without a new reviewed pin")
    if notice_raw != selector.notice_bytes(manifest):
        die("NOTICE does not bind the exact shipped manifest")

    rigs = manifest.get("rigs")
    if not isinstance(rigs, list) or tuple(rig.get("id") for rig in rigs) != EXPECTED_PERSONAS:
        die("the fixed 17-person roster or order changed")
    layers = [layer for rig in rigs for layer in rig.get("layers", [])]
    totals = manifest.get("totals")
    if not isinstance(totals, dict):
        die("totals are missing")
    expected_totals = {
        "rigs": len(EXPECTED_PERSONAS),
        "layers": EXPECTED_LAYERS,
        "png_files": EXPECTED_LAYERS,
        "png_bytes": EXPECTED_PNG_BYTES,
    }
    if totals != expected_totals or len(layers) != EXPECTED_LAYERS:
        die(f"unexpected totals: {totals!r}")

    listed: set[str] = set()
    measured_bytes = 0
    for rig in rigs:
        persona = rig["id"]
        canvas = rig.get("canvas")
        if canvas != {"height": 1280, "width": 1280}:
            die(f"{persona}: canvas changed")
        if rig.get("viewport") != {"height": 1280, "width": 1280, "x": 0, "y": 0}:
            die(f"{persona}: approved desktop viewport changed")
        render_slots: set[int] = set()
        for layer in rig["layers"]:
            if layer.get("role") not in {"body", "mouth", "eye", "brow"}:
                die(f"{persona}: unknown runtime layer role")
            render_z = layer.get("render_z")
            if not isinstance(render_z, int) or render_z < 0 or render_z in render_slots:
                die(f"{persona}: render_z is invalid or duplicated")
            render_slots.add(render_z)
            relative = layer.get("file")
            if not isinstance(relative, str):
                die(f"{persona}: layer path is missing")
            path = PurePosixPath(relative)
            if (
                path.is_absolute()
                or len(path.parts) != 3
                or path.parts[:2] != ("rigs", persona)
                or path.suffix != ".png"
                or ".." in path.parts
            ):
                die(f"{persona}: unsafe layer path {relative!r}")
            if relative in listed:
                die(f"duplicate layer path {relative}")
            listed.add(relative)
            info = selector.inspect_png(BUNDLE / path)
            if info["bytes"] != layer.get("bytes") or info["sha256"] != layer.get("sha256"):
                die(f"{relative}: bytes or SHA-256 changed")
            if info["width"] != layer.get("width") or info["height"] != layer.get("height"):
                die(f"{relative}: pixel dimensions changed")
            measured_bytes += info["bytes"]
        if render_slots != {layer["z"] for layer in rig["layers"]}:
            die(f"{persona}: canonical rendering changed the available z slots")
    if measured_bytes != EXPECTED_PNG_BYTES:
        die(f"PNG byte total changed to {measured_bytes}")

    actual = {
        path.relative_to(BUNDLE).as_posix()
        for path in BUNDLE.rglob("*")
        if path.is_file()
    }
    expected = listed | {"manifest.json", "manifest.js", "NOTICE.md"}
    if actual != expected:
        die(f"unlisted or missing bundle files: {sorted(actual ^ expected)!r}")

    runtime = (BUNDLE / "manifest.js").read_text(encoding="utf-8")
    if not runtime.startswith(RUNTIME_PREFIX) or not runtime.endswith(";\n"):
        die("runtime manifest wrapper changed")
    runtime_manifest = json.loads(runtime[len(RUNTIME_PREFIX) : -2])
    if runtime_manifest != manifest:
        die("manifest.js is not the exact manifest.json projection")

    print(
        f"persona reels: {len(rigs)} rigs, {len(layers)} layers, "
        f"{measured_bytes} PNG bytes; hashes and rights projection match"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
